# coding: utf-8

"""
    trieve-server

    Trieve REST API OpenAPI Documentation

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from arguflow.models.search_chunk_data import SearchChunkData

class TestSearchChunkData(unittest.TestCase):
    """SearchChunkData unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SearchChunkData:
        """Test SearchChunkData
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SearchChunkData`
        """
        model = SearchChunkData()
        if include_optional:
            return SearchChunkData(
                cross_encoder = True,
                date_bias = True,
                filters = None,
                link = [
                    ''
                    ],
                page = 0,
                query = '',
                search_type = '',
                tag_set = [
                    ''
                    ],
                time_range = [
                    null
                    ],
                weights = [
                    null
                    ]
            )
        else:
            return SearchChunkData(
                query = '',
                search_type = '',
        )
        """

    def testSearchChunkData(self):
        """Test SearchChunkData"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
