# coding: utf-8

"""
    trieve-server

    Trieve REST API OpenAPI Documentation

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from trieve_python_client.api.file_api import FileApi


class TestFileApi(unittest.TestCase):
    """FileApi unit test stubs"""

    def setUp(self) -> None:
        self.api = FileApi()

    def tearDown(self) -> None:
        pass

    def test_delete_file_handler(self) -> None:
        """Test case for delete_file_handler

        delete_file
        """
        pass

    def test_get_file_handler(self) -> None:
        """Test case for get_file_handler

        get_file
        """
        pass

    def test_get_image_file(self) -> None:
        """Test case for get_image_file

        get_image_file
        """
        pass

    def test_upload_file_handler(self) -> None:
        """Test case for upload_file_handler

        upload_file
        """
        pass


if __name__ == '__main__':
    unittest.main()
