# coding: utf-8

"""
    trieve-server

    Trieve REST API OpenAPI Documentation

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from trieve_python_client.api.chunk_api import ChunkApi


class TestChunkApi(unittest.TestCase):
    """ChunkApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ChunkApi()

    def tearDown(self) -> None:
        pass

    def test_create_chunk(self) -> None:
        """Test case for create_chunk

        create_chunk
        """
        pass

    def test_create_suggested_queries_handler(self) -> None:
        """Test case for create_suggested_queries_handler

        get_suggested_queries
        """
        pass

    def test_delete_chunk(self) -> None:
        """Test case for delete_chunk

        delete_chunk
        """
        pass

    def test_delete_chunk_by_tracking_id(self) -> None:
        """Test case for delete_chunk_by_tracking_id

        delete_chunk_by_tracking_id
        """
        pass

    def test_generate_off_chunks(self) -> None:
        """Test case for generate_off_chunks

        generate_off_chunks
        """
        pass

    def test_get_chunk_by_id(self) -> None:
        """Test case for get_chunk_by_id

        get_chunk
        """
        pass

    def test_get_chunk_by_tracking_id(self) -> None:
        """Test case for get_chunk_by_tracking_id

        get_chunk_by_tracking_id
        """
        pass

    def test_get_recommended_chunks(self) -> None:
        """Test case for get_recommended_chunks

        get_recommended_chunks
        """
        pass

    def test_search_chunk(self) -> None:
        """Test case for search_chunk

        search
        """
        pass

    def test_update_chunk(self) -> None:
        """Test case for update_chunk

        update_chunk
        """
        pass

    def test_update_chunk_by_tracking_id(self) -> None:
        """Test case for update_chunk_by_tracking_id

        update_chunk_by_tracking_id
        """
        pass


if __name__ == '__main__':
    unittest.main()
