# coding: utf-8

"""
    trieve-server

    Trieve REST API OpenAPI Documentation

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from arguflow.api.organization_api import OrganizationApi


class TestOrganizationApi(unittest.TestCase):
    """OrganizationApi unit test stubs"""

    def setUp(self) -> None:
        self.api = OrganizationApi()

    def tearDown(self) -> None:
        pass

    def test_create_organization(self) -> None:
        """Test case for create_organization

        create_organization
        """
        pass

    def test_get_organization_by_id(self) -> None:
        """Test case for get_organization_by_id

        get_organization
        """
        pass

    def test_get_organization_usage(self) -> None:
        """Test case for get_organization_usage

        get_organization_usage
        """
        pass

    def test_get_organization_users(self) -> None:
        """Test case for get_organization_users

        get_organization_users
        """
        pass

    def test_update_organization(self) -> None:
        """Test case for update_organization

        update_organization
        """
        pass


if __name__ == '__main__':
    unittest.main()
