# coding: utf-8

"""
    trieve-server

    Trieve REST API OpenAPI Documentation

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from trieve_python_client.api.invitation_api import InvitationApi


class TestInvitationApi(unittest.TestCase):
    """InvitationApi unit test stubs"""

    def setUp(self) -> None:
        self.api = InvitationApi()

    def tearDown(self) -> None:
        pass

    def test_post_invitation(self) -> None:
        """Test case for post_invitation

        send_invitation
        """
        pass


if __name__ == '__main__':
    unittest.main()
