# coding: utf-8

"""
    trieve-server

    Trieve REST API OpenAPI Documentation

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from arguflow.models.create_message_data import CreateMessageData

class TestCreateMessageData(unittest.TestCase):
    """CreateMessageData unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CreateMessageData:
        """Test CreateMessageData
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CreateMessageData`
        """
        model = CreateMessageData()
        if include_optional:
            return CreateMessageData(
                model = '',
                new_message_content = '',
                topic_id = ''
            )
        else:
            return CreateMessageData(
                new_message_content = '',
                topic_id = '',
        )
        """

    def testCreateMessageData(self):
        """Test CreateMessageData"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
