# coding: utf-8

"""
    trieve-server

    Trieve REST API OpenAPI Documentation

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from trieve_python_client.api.notifications_api import NotificationsApi


class TestNotificationsApi(unittest.TestCase):
    """NotificationsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = NotificationsApi()

    def tearDown(self) -> None:
        pass

    def test_get_notifications(self) -> None:
        """Test case for get_notifications

        get_notifications
        """
        pass

    def test_mark_all_notifications_as_read(self) -> None:
        """Test case for mark_all_notifications_as_read

        mark_all_read
        """
        pass

    def test_mark_notification_as_read(self) -> None:
        """Test case for mark_notification_as_read

        mark_read
        """
        pass


if __name__ == '__main__':
    unittest.main()
