# coding: utf-8

"""
    trieve-server

    Trieve REST API OpenAPI Documentation

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from arguflow.api.stripe_api import StripeApi


class TestStripeApi(unittest.TestCase):
    """StripeApi unit test stubs"""

    def setUp(self) -> None:
        self.api = StripeApi()

    def tearDown(self) -> None:
        pass

    def test_cancel_subscription(self) -> None:
        """Test case for cancel_subscription

        """
        pass

    def test_direct_to_payment_link(self) -> None:
        """Test case for direct_to_payment_link

        """
        pass

    def test_get_all_plans(self) -> None:
        """Test case for get_all_plans

        """
        pass

    def test_update_subscription_plan(self) -> None:
        """Test case for update_subscription_plan

        """
        pass


if __name__ == '__main__':
    unittest.main()
