# coding: utf-8

"""
    trieve-server

    Trieve REST API OpenAPI Documentation

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from arguflow.api.message_api import MessageApi


class TestMessageApi(unittest.TestCase):
    """MessageApi unit test stubs"""

    def setUp(self) -> None:
        self.api = MessageApi()

    def tearDown(self) -> None:
        pass

    def test_create_message_completion_handler(self) -> None:
        """Test case for create_message_completion_handler

        create_message
        """
        pass

    def test_edit_message_handler(self) -> None:
        """Test case for edit_message_handler

        edit_message
        """
        pass

    def test_get_all_topic_messages(self) -> None:
        """Test case for get_all_topic_messages

        get_all_messages
        """
        pass

    def test_regenerate_message_handler(self) -> None:
        """Test case for regenerate_message_handler

        regenerate_message
        """
        pass


if __name__ == '__main__':
    unittest.main()
