# coding: utf-8

"""
    trieve-server

    Trieve REST API OpenAPI Documentation

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from arguflow.models.generate_chunks_request import GenerateChunksRequest

class TestGenerateChunksRequest(unittest.TestCase):
    """GenerateChunksRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GenerateChunksRequest:
        """Test GenerateChunksRequest
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GenerateChunksRequest`
        """
        model = GenerateChunksRequest()
        if include_optional:
            return GenerateChunksRequest(
                chunk_ids = [
                    ''
                    ],
                model = '',
                prev_messages = [
                    arguflow.models.chat_message_proxy.ChatMessageProxy(
                        content = '', 
                        role = '', )
                    ]
            )
        else:
            return GenerateChunksRequest(
                chunk_ids = [
                    ''
                    ],
                prev_messages = [
                    arguflow.models.chat_message_proxy.ChatMessageProxy(
                        content = '', 
                        role = '', )
                    ],
        )
        """

    def testGenerateChunksRequest(self):
        """Test GenerateChunksRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
