# coding: utf-8

"""
    trieve-server

    Trieve REST API OpenAPI Documentation

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from arguflow.api.topic_api import TopicApi


class TestTopicApi(unittest.TestCase):
    """TopicApi unit test stubs"""

    def setUp(self) -> None:
        self.api = TopicApi()

    def tearDown(self) -> None:
        pass

    def test_create_topic(self) -> None:
        """Test case for create_topic

        create_topic
        """
        pass

    def test_delete_topic(self) -> None:
        """Test case for delete_topic

        delete_topic
        """
        pass

    def test_get_all_topics(self) -> None:
        """Test case for get_all_topics

        get_all_topics
        """
        pass

    def test_update_topic(self) -> None:
        """Test case for update_topic

        update_topic
        """
        pass


if __name__ == '__main__':
    unittest.main()
