# coding: utf-8

"""
    trieve-server

    Trieve REST API OpenAPI Documentation

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from arguflow.api.user_api import UserApi


class TestUserApi(unittest.TestCase):
    """UserApi unit test stubs"""

    def setUp(self) -> None:
        self.api = UserApi()

    def tearDown(self) -> None:
        pass

    def test_delete_user_api_key(self) -> None:
        """Test case for delete_user_api_key

        delete_user_api_key
        """
        pass

    def test_get_user_files_handler(self) -> None:
        """Test case for get_user_files_handler

        get_user_files
        """
        pass

    def test_get_user_with_chunks_by_id(self) -> None:
        """Test case for get_user_with_chunks_by_id

        get_user_chunks
        """
        pass

    def test_set_user_api_key(self) -> None:
        """Test case for set_user_api_key

        set_user_api_key
        """
        pass

    def test_update_user(self) -> None:
        """Test case for update_user

        update_user
        """
        pass


if __name__ == '__main__':
    unittest.main()
