# coding: utf-8

"""
    trieve-server

    Trieve REST API OpenAPI Documentation

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from trieve_python_client.api.auth_api import AuthApi


class TestAuthApi(unittest.TestCase):
    """AuthApi unit test stubs"""

    def setUp(self) -> None:
        self.api = AuthApi()

    def tearDown(self) -> None:
        pass

    def test_callback(self) -> None:
        """Test case for callback

        openid_callback
        """
        pass

    def test_get_me(self) -> None:
        """Test case for get_me

        get_me
        """
        pass

    def test_login(self) -> None:
        """Test case for login

        login
        """
        pass

    def test_logout(self) -> None:
        """Test case for logout

        logout
        """
        pass


if __name__ == '__main__':
    unittest.main()
