# coding: utf-8

"""
    trieve-server

    Trieve REST API OpenAPI Documentation

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, StrictBool, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class FileUploadCompletedNotificationWithName(BaseModel):
    """
    FileUploadCompletedNotificationWithName
    """ # noqa: E501
    collection_name: Optional[StrictStr] = None
    collection_uuid: StrictStr
    created_at: datetime
    id: StrictStr
    updated_at: datetime
    user_read: StrictBool
    user_uuid: StrictStr
    __properties: ClassVar[List[str]] = ["collection_name", "collection_uuid", "created_at", "id", "updated_at", "user_read", "user_uuid"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of FileUploadCompletedNotificationWithName from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if collection_name (nullable) is None
        # and model_fields_set contains the field
        if self.collection_name is None and "collection_name" in self.model_fields_set:
            _dict['collection_name'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of FileUploadCompletedNotificationWithName from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "collection_name": obj.get("collection_name"),
            "collection_uuid": obj.get("collection_uuid"),
            "created_at": obj.get("created_at"),
            "id": obj.get("id"),
            "updated_at": obj.get("updated_at"),
            "user_read": obj.get("user_read"),
            "user_uuid": obj.get("user_uuid")
        })
        return _obj


